ktor:
  application:
    modules:
      - dev.ixor.callie.ApplicationKt.module
  deployment:
    port: 8080
  development: true

database:
  driverClassName: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://localhost:5432/callie_server"
  username: "callie"
  password: "callie"
